# Introduction {#intro}

VisionEval differs from traditional travel demand models both in how it works and what kind of planning concerns it helps to address. This **Concepts Primer** provides a quick introduction approach to the unique features and applications of VisionEval. It reviews the main model components and key concepts at a high level, to assist new users in understanding concepts they will apply as they set up scenarios, develop inputs and evaluate outputs.  Links to more detailed documentation will allow the reader to delve further into each topic, as they choose.

## What can I do with VisionEval?

Structurally, VisionEval may be described as a "disaggregate demand/aggregate supply" model. That is, it combines rich demographic and socioeconomic detail from a synthetic population with aggregate treatments of travel (multi-modal VMT and congestion without explicit trips, or transport networks). The implication of the "aggregate supply" model is that VisionEval cannot be used to evaluate performance of specific projects or corridors.

What VisionEval can do, and even makes especially simple, is to evaluate large numbers of scenarios and explore how combinations of alternative future conditions might affect performance measures. Travel demand models, whether built using traditional trip-based or more contemporary activity-based techniques, sacrifice network detail for flexibility. It is difficult in such models to capture novel behaviors such as an increased propensity to use inexpensive ride-hailing services, or to express shifts in vehicle ownership and occupancy that may be influenced by multiple factors some of which have not yet been observed. Yet these potential shifts are often very important for assessing the potential of pricing, investment strategies or other policy priorities. VisionEval also makes it relatively simple to explore risks and opportunities that may eventually be realized as new transportation options mature.

VisionEval won't help us determine if a particular highway segment should be built or upgraded, or what kind of transit service improvements should be extended into new areas. But it can help us look at the market for new technologies, and explore future scenarios that are based both on changed circumstances (altered demographics, increased congestion, or alternate road pricing strategies) as well as on changed behaviors (including behaviors that _might_ happen, but that we have not yet observed because the key enabling technologies are too early in their deployment). VisionEval results can be explored in detail by market segment, asking questions about how benefits might be distributed regionally, and what overall system performance might look like.

Ultimately, VisionEval is a system for asking a very broad range of "what if" questions about how the transportation system might perform, and how its benefits and costs might be distributed over the community.  It can efficiently process hundreds of scenarios looking at many different types of interventions, alternative policies, and hypothetical future conditions and travel behaviors. The results can inform strategic questions, helping decision makers answer questions such as "What are our options for achieving this performance result?" or "What are our risks if new transportation technologies develop in these different ways?"

Using VisionEval to answer such questions does not make other types of modeling obsolete (such as travel demand models or corridor microsimulations). Instead, it helps to determine what is worth the effort to code into these more detailed models, and also to explore and document novel assumptions about the future that may require extra effort to implement, and that would be prohibitively expensive to explore through traditional planning models.

## Strengths and limitations

VisionEval operates at broad geographic levels and without explicit network representations to enable very fast analyses across scores of different assumptions and inputs. It is especially well suited for quickly evaluating several different combinations of policies or assessing the range of impacts when uncertainty exists in several key inputs. Because much of the travel behavior is asserted based on observed travel patterns the latter can be changed to reflect expected changes due to new technologies, services, and expected changes in behavior over time. Thus, VisionEval is better suited than traditional travel modeling approaches for certain pursuits:

+ Screening a wide range of policy actions, especially in the face of uncertainties where ranges of expected responses or effects must be considered
+ Resilience testing under uncertainties (e.g., population growth, household size, fuel prices)
+ Directly "comparing and contrasting" broad ranges or combinations of policies (e.g., ITS, transit service, active transport, demand management)
+ Analysis of broad policy or technology changes (e.g., carbon taxes, low-carbon fuels)
+ Evaluating fuel consumption, particulate emissions, and greenhouse gas emissions impacts of proposed policies

However, VisionEval is not well suited for detailed geographic analyses, to include the effects of congestion on individual trips or tours. Thus, examining the effects of localized land use or network assumptions cannot be carried out using VisionEval. Improvements in network capacity, efficiency, or safety can only be indirectly incorporated in VisionEval. 

## VisionEval geographies

Traditional travel forecasting models divide a study area into thousands of traffic analysis zones in order to facilitate highly granular spatial analyses. This allows trip (tour segment) origins and destinations to enter and exit a detailed representation of the multimodal transportation network in order to study network flows, congestion, and efficiency outcomes. VisionEval operates at a much broader spatial scale, using several levels of geography:

+ A `region` defines the entire area covered by the VisionEval analyses
+ `Azone`s are large areas such as cities, counties, or Public Use Microdata Areas (PUMAs)
+ `Bzone`s are subdivisions of Azones that represent neighborhoods, Census tracts or block groups, or other relatively homogenous areas
+ [<span style="color:green">Metropolitan areas</span>][lexicon] (Marea) are defined as groups of Azones that define them

The _location type_ of each household is also coded as urban, town, or rural areas. A _place type_ is also defined in terms of urban density and its mix of jobs and housing. Both are usually defined for each Bzone used in the model.

> Watch a [video presentation](https://youtu.be/-ylFbyLfhbw?t=4690) with more information about VisionEval geographies

## Performance metrics

The following table summarizes many of the possible performance metrics that can be summarized at the region level. The ability to easily export the data enables the analyst to construct new or different performance measures easily. 

+ Mobility
    + Daily VMT per capita
    + Annual walk trips per capita
    + Daily Bike trips per capita

+ Economy
    + Annual all vehicle delay per capita (hours)
    + Daily household [<span style="color:green">parking costs</span>][lexicon]
    + Annual household [<span style="color:green">vehicle operating cost</span>][lexicon] (fuel, taxes, parking)
    + Annual household [<span style="color:green">auto ownership costs</span>][lexicon] (depreciation, vehicle maintenance, tires, finance charge, insurance, registration)

+ Land Use
    + Number or percent of residents living in [<span style="color:green">mixed use</span>][lexicon] areas
    + Number of dwelling by housing type (e.g., single family [SF], multi-family [MF])

+ Environmental
    + Annual greenhouse gas emissions per capita
    + Household vehicle greenhouse gas/mile
    + Commercial vehicle greenhouse gas/mile
    + Transit vehicle greenhouse gas/mile

+ Energy
    + Annual per capita fuel consumption for all vehicles (gallons)
    + Average [<span style="color:green">fuel efficiency</span>][lexicon] (net miles per gallon) for all vehicles
    + Annual external [<span style="color:green">social costs</span>][lexicon] per households (total/percent paid)

<!-- 
_Specific list of metrics under each category above could correspond to standard CSV/GUI outputs we are working on. ODOT outputs use classification above, like in [RV Strategic Assessment Report](https://www.rvmpo.org/images/studies/2015-strategic-assessment/Strategic_Asessment_Final_Report.pdf)  (Table 2 basic scenarios & appendix Table 3C for selected unidimensional multiruns)._
-->
