# Typical applications

VisionEval can be used to inform planning in several different realms, as described in the following sections. 

## Strategic modeling

VisionEval is a strategic modeling system. It differs from traditional travel demand and microsimulation models principally in that it is applied earlier in the planning process, and it is used for different purposes. Rather than examining the detailed performance of specific facilities (assessing individual projects), VisionEval estimates regional and small area performance metrics that reflect overarching policy goals such as emission reduction, regional VMT, or mode share. 

Traditional travel models used for planning purposes are applied to estimate outcomes under a small number of alternate input scenarios that vary either land use (socioeconomic data) or characteristics of the transportation network (alignment, land configuration, tolls, etc.). In these models, the response to the changed inputs is estimated based on parameters typically derived from household surveys and other related data sources: that is, the behavior in the model is presumed to be what we see today. Even though such models are often behaviorally complex (e.g., activity-based models), the effort required to assess many alternative scenarios is often prohibitive, and because such models are built using complex estimation procedures rooted in detailed data about existing behavior, it can be technically difficult or impossible to reliably encode possible future shifts in behavior, or to explore alternative possible future behaviors.

VisionEval is typically set up to run many scenarios that explore a broad set of alternative policies and investment priorities that may result from a variety of possible categories of policy and project interventions, or from a range of possible future conditions (strong or weak economic growth, demographics that shift at different rates), or from uncertain deployment of new technologies such as app-based ridesharing (Transportation Network Companies or TNCs).

A full application of VisionEval may examine hundreds or even thousands of permutations of inputs representing many possible future outcomes. The outputs allow planners and decision-makers to explore the outcomes of each scenario compared to the others. so they can visualize and discuss the relative impact and cross-influences, as well as the unintended consequences, of factors represented across the scenarios. VisionEval allows planners to assess alternative assumptions about uncertain phenomena such as AV deployment, it is a very effective tool for identifying risks and opportunities, as well as for formulating effective strategic responses to new challenges for which little current data exists or for which many outcomes are possible yet none are certain. The most interesting of the resulting strategic plans can be refined with more detailed models. Based on the strategic modeling findings, uncertainties can be confidently simplified into a smaller number of scenarios to explore in detail.

Notwithstanding its typical application as a strategic model, VisionEval does allow detailed investigation of certain phenomena such as fleet composition and vehicle ownership in relation to Greenhouse Gas Analysis. It also is unique in its ability to explore budget constraints on travel. Its simulation of individual households enables it to assess policies that would be difficult or impossible to model successfully with traditional models. 

## Local policy actions

VisionEval is well suited for evaluating a wide range of local policies at varying levels of geography: 

+ Demographics (Azone)
    + Population by age (households & non-institutional group quarters)
    + Average household size and percent of single-person households
    + Licensure drivers rate (optional)
    + Average per capita Income

+ LandUse (Bzone)
    + Employment by type (Total, Retail, Service)
    + [<span style="color:green">Dwelling units</span>][lexicon] by type (SF, MF)
    + Income quartiles (for allocating households to [<span style="color:green">Dwelling units</span>][lexicon])
    + Share of households in [<span style="color:green">Urban Mixed Use</span>][lexicon] areas (optional)
    + [<span style="color:green">5D built form measures</span>][lexicon] (Design & Transit)
    + Acres, centroid latitude and longitude

+ Actions
    + [<span style="color:green">Road lane-miles</span>][lexicon] (freeways, arterials) (Marea)
    + [<span style="color:green">Transit Service</span>][lexicon] (service miles by transit mode) (Marea)
    + [<span style="color:green">Short Trips SOV Diversion</span>][lexicon]Short Trips SOV Diversion costs, substitutability & access time (Azone)
    + [<span style="color:green">Short Trips SOV Diversion</span>][lexicon] (bike, personal electrics, etc.) (Azone)
    + [<span style="color:green">ITS</span>][lexicon] Operations (Ramp metering, Incident response, (Marea)
    + ITS [<span style="color:green">speed smoothing</span>][lexicon] (Freeway ATM, Art Signal optimization) (Marea)
    + VMT covered by Drivers in [<span style="color:green">Eco-Drive</span>][lexicon] programs (Marea)
    + EV Charging infrastructure (residential) (Azone)

+ Pricing
    + Fuel and electricity costs (Azone)
    + Road Cost Recovery – Registration Fee, gas taxes, VMT fee (Azone)
    + [<span style="color:green">Carbon Pricing </span>][lexicon](social cost recovery) (Region)
    + [<span style="color:green">Congestion Fees</span>][lexicon] (Marea)
    + [<span style="color:green">PAYD insurance</span>][lexicon] participation (Azone)

+ Vehicle, Fuels, & Emissions
    + Electricity [<span style="color:green">carbon intensity</span>][lexicon] (Azone)
    + Fuel [<span style="color:green">carbon intensity</span>][lexicon] (composites by vehicle group) (Region)
    + LDV-HH percent Light Trucks (stock) (Azone)
    + LDV-HH [<span style="color:green">vehicle age</span>][lexicon] average (Azone)
    + LDV CarService, vehicle mix (stock) (Region)
    + Transit vehicles & fuels mix (Marea)
    + LDV CommService vehicle mix, %Light Trucks (stock) (Region)
    + [<span style="color:green">Heavy truck</span>][lexicon] vehicle mix (stock) (Region)

## Scenario analyses

A key value of VisionEval is how it facilitates running many scenarios or possible futures.  In practices, the user typically starts by setting up the model with a reference scenario, best estimate of future conditions. The model can be validated at this point. This Reference scenario then serves as a pivot point for manual or automated scenario testing. Typically that includes a mix of the following, reflecting “what if?” type questions:

+ Sensitivity tests (manual): Ad hoc tests that change a single category of inputs for each run
+ Combination scenarios (automated): Several combinations of categories combined

Note that the number of combinations scenarios grows quickly, in a multiplicative manner.  For instance, all combinations of 3 levels each of land use transit, bike, parking, and TDM policies and 3 fuel price scenarios would result in 243 scenarios (3x3x3x3x3). For this reason, _categories_ are often used that combine multiple inputs. Automated processes aid in the set-up and running of these scenarios, which the analyst can use a variety of data mining and visualization tools to explore the results. 
