# Adjustments

## Congestion adjustments

Congestion, only calculated on urbanized roads (a subset of [<span style="color:green">metropolitan area</span>][lexicon] roads, requires estimating and combining together the VMT of all [<span style="color:green">vehicle groups</span>][lexicon]. For non-household vehicles, base year VMT is calculated directly from inputs and model parameters, while future year is a function of the input [<span style="color:green">growth basis</span>][lexicon]. Initial allocations of DMVT across [<span style="color:green">road class</span>][lexicon] is based on input values. 

Light duty vehicle (LDV) VMT is allowed to re-allocate between freeways and arterials to balance demand (VMT) and roadway supply (lane-miles) through a generalized cost framework (including roadway speed and congestion fees, if any). Roadway supply (i.e., capacity) is adjusted by delay-reducing [<span style="color:green">ITS</span>][lexicon] operations policies based on [<span style="color:green">fuel-speed curves</span>][lexicon] by [<span style="color:green">powertrain</span>][lexicon], the resulting congested speeds impact vehicle [<span style="color:green">fuel efficiency</span>][lexicon]. Further adjustments are applied to reflect any [<span style="color:green">speed smoothing</span>][lexicon] and [<span style="color:green">EcoDrive</span>][lexicon] programs that may not affect delay but reduce acceleration and deceleration with associated impacts on fuel efficiency.

No fuel efficiency adjustments for congestion or policies are made to non-urban roadway VMT.  The delays faced by each household and associated fuel economy impacts are applied to each individual household's VMT and vehicles. Resulting overall average speeds, delays, and DMVT proportions, by [<span style="color:green">road class</span>][lexicon] at each [<span style="color:green">congestion level</span>][lexicon] on urbanized and other roads are also tabulated along with the resulting average per mile [<span style="color:green">congestion fees</span>][lexicon] paid, if any, and overall vehicle hours of delay (VHD) by [<span style="color:green">vehicle group</span>][lexicon].

> Watch a [video summary](https://youtu.be/-ylFbyLfhbw?t=8401) of VisionEval's congestion adjustment

### Initialize roadway conditions

The roadway conditions in the model are calculated in three steps:

1. [_Load Default Road VMT Values:_](github.com/gregorbj/Archive-VisionEval/blob/develop/api/VE_Training_March_13-14_2019/VE_Training.md#91-loaddefaultroadVMTvalues)  These calculations are completed before the model run starts. The base year roadway VMT is processed, including light duty vehicle and [<span style="color:green">heavy truck</span>][lexicon] VMT by state and urbanized area as well as VMT proportions by urbanized area, [<span style="color:green">vehicle group</span>][lexicon] (light duty vehicle, heavy truck, bus), and [<span style="color:green">road class</span>][lexicon]. The user can either provide direct inputs for these values or specify a state and/or urbanized area and the model will use default data from the [20xx USDOT Highway Statistics](https://github.com/VisionEval/VisionEval/tree/master/sources/modules/VETravelPerformance/inst/extdata/sources), where available.
2. [_Initialize:_](https://github.com/gregorbj/Archive-VisionEval/blob/develop/api/VE_Training_March_13-14_2019/VE_Training.md#92-initialize-module). This step is run when the model run is initialized. User inputs used by several modules are read and checked (many with several valid options, proportions sum to 1, consistency, congestion fees increase with congestion level). Some of these values are optional, using default data where not specified. This includes various assumptions on base year VMT within both [<span style="color:red">urbanized area(s)</span>][lexicon] and the full model region, by [<span style="color:green">vehicle group</span>][lexicon], allocation among [<span style="color:green">road class</span>][lexicon], [<span style="color:green">growth basis</span>][lexicon], and assumptions for [<span style="color:green">freight vehicle groups</span>][lexicon]. It also checks inputs on [<span style="color:green">ITS</span>][lexicon] operational policies and [<span style="color:green">EcoDriving</span>][lexicon] programs, including any user-specified "other ops" programs and [<span style="color:green">congestion fees</span>][lexicon] (by road class and [<span style="color:green">congestion level</span>][lexicon]). 
3. [_Calculate Road VMT:_](https://github.com/gregorbj/Archive-VisionEval/blob/develop/api/VE_Training_March_13-14_2019/VE_Training.md#93-calculateroadVMT-module)  Adds together [<span style="color:green">metropolitan area</span>][lexicon] VMT of all [<span style="color:green">vehicle groups</span>][lexicon] (Households, CarService, Commercial Service, Heavy Truck, Transit) and allocates it across [<span style="color:green">road classes</span>][lexicon] (freeway, arterial, other), limiting it to urbanized area roadways for use in congestion calculations. To do so, several factors are established in the base year.  One uses the input [<span style="color:green">growth basis</span>][lexicon] (population, income, household VMT) to estimate future year [<span style="color:green">freight vehicle group</span>][lexicon] (commercial service and heavy truck) VMT (using input base year VMT values by region and Marea, if provided, model-estimates otherwise). A second base year factor identifies the urban and non-urban allocation of VMT from [<span style="color:green">metropolitan area</span>][lexicon] households and related commercial service vehicles. For Heavy Trucks VMT an input specifies the proportion of VMT on urbanized roads while transit VMT (of all [<span style="color:green">transit service modes</span>][lexicon]) is assumed to only occur on urbanized roads. Base year allocations of urban VMT by [<span style="color:green">vehicle group</span>][lexicon] among [<span style="color:green">road classes</span>][lexicon] are based on input shares, subject to adjustment during subsequent congestion calculations. Finally, to assess delay faced by each household and associated fuel efficiency impacts, each individual household's VMT is split between miles on urbanized and other road miles.

### Congestion model and adjustments

Three adjustments are made based on congestion levels:

1. [_Calculate Road Performance:_](https://github.com/gregorbj/Archive-VisionEval/blob/develop/api/VE_Training_March_13-14_2019/VE_Training.md#94-calculateroadperformance-module)  [<span style="color:green">Congestion level</span>][lexicon] by [<span style="color:green">road class</span>][lexicon] and the associated amounts of VMT are iteratively estimated. Light duty vehicle (LDV) VMT is allowed to re-allocate between freeways and arterials to balance demand and roadway supply (lane-miles) through a generalized cost framework (including roadway speed and congestion fees, if any and an estimated base year urbanized area [<span style="color:green">lambda parameter</span>][lexicon] based on the area's population and freeway-arterial lane-mile ratio). DMVT allocation at different aggregate demand-supply ratios relies on data from the [2009 Urban Mobility Study (UMS)](https://static.tti.tamu.edu/tti.tamu.edu/documents/umr/archive/mobility-report-2009-wappx.pdf) for 90 urbanized areas, where the model chooses the 5-10 cities with most similar congestion ratios.

    The supply calculation considers the delay-reduction effects of deploying urban area [<span style="color:green">ITS</span>][lexicon] operations programs (freeway ramp metering, freeway incident management, arterial signal coordination, arterial access control or user-defined "other ops" programs. The standard ITS-operations program impacts are based on research ([Bigazzi & Clifton 2011](https://github.com/VisionEval/VisionEval/tree/master/sources/modules/VETravelPerformance/inst/extdata/sources)). Non-urban speeds are also calculated, using a simple ratio of rural-to-urban travel volumes.
    
    The resulting average speeds, delay and DMVT proportions, by [<span style="color:green">road class</span>][lexicon] at each [<span style="color:green">congestion level</span>][lexicon] on urbanized and other metropolitan area roads are calculated, as is the resulting average per mile [<span style="color:green">congestion fees</span>][lexicon] paid, if any, and overall VHD by [<span style="color:green">vehicle group</span>][lexicon].

2. [_Calculate Mpg Mpkwh Adjustments:_](https://github.com/gregorbj/Archive-VisionEval/blob/develop/api/VE_Training_March_13-14_2019/VE_Training.md#95-calculatempgmpkwhadjustments-module)  Adjustments to [<span style="color:green">fuel efficiency</span>][lexicon] (MPG and MPKwhr) for all [<span style="color:green">vehicle groups</span>][lexicon] resulting from traffic congestion, [<span style="color:green">congestion fees</span>][lexicon], ITS [<span style="color:green">speed smoothing</span>][lexicon] (i.e. active traffic management which reduces speed variation), and [<span style="color:green">EcoDriving</span>][lexicon] are calculated. The [<span style="color:green">fuel-speed curves</span>][lexicon] vary by [<span style="color:green">road class</span>][lexicon], congestion [<span style="color:green">powertrains</span>][lexicon] (LdIce, LdHev, LdEv, HdIce) and, where applicable, [<span style="color:green">vehicle type</span>][lexicon] relative to reference speeds by [<span style="color:green">road class</span>][lexicon]. The adjustments are based on drive-cycle level simulation research ([Bigazzi & Clifton 2011](https://github.com/VisionEval/VisionEval/tree/master/sources/modules/VETravelPerformance/inst/extdata/sources)). Note that no adjustments are made for [<span style="color:green">ITS</span>][lexicon] policies (standard and speed smoothing policies) or [<span style="color:green">EcoDrive</span>][lexicon] programs on 'other' road classes (non-freeway or arterials) and non-urbanized roads, which are assumed to be uncongested. 
3. [_Adjust Household Vehicle MPg Mpkwh:_](https://github.com/gregorbj/Archive-VisionEval/blob/develop/api/VE_Training_March_13-14_2019/VE_Training.md#96-adjusthhvehiclempgmpkwh-module)  Implements the [<span style="color:green">fuel efficiency</span>][lexicon] (MPG and MPKwh) adjustments of household vehicles (including Car Service VMT), reflecting the effects of congestion, [<span style="color:green">congestion fees</span>][lexicon], ITS [<span style="color:green">speed smoothing</span>][lexicon], and [<span style="color:green">eco-driving</span>][lexicon] that were calculated elsewhere. These adjustments vary by vehicle [<span style="color:green">powertrain</span>][lexicon], [<span style="color:green">vehicle type</span>][lexicon], and the proportion of the household's travel that is driven on urban and non-urban roads within the [<span style="color:green">metropolitan area</span>][lexicon]. Joint effects are calculated as the product of congestion speed effects and the maximum of implemented speed-smoothing policies (eco-driving & ITS-speed smoothing).

## Household costs and budgets {#household-costs-and-budgets}

Two adjustments are made in response to household budgets. [<span style="color:green">Auto ownership costs</span>][lexicon] are calculated and an adjustment is made to the number of household owned autos if the costs are less than switching to a 'High' level [<span style="color:green">Car Service</span>][lexicon], where available (subject to input limits on [<span style="color:green">Car Service</span>][lexicon] substitutability). [<span style="color:green">Vehicle ownership costs</span>][lexicon] include financing, depreciation, insurance (unless in [<span style="color:green">PAYD program</span>][lexicon]), annual registration fees, and residential parking fees.

Additionally, in order to respond to pricing policies and energy costs, VisionEval imposes a budget limitation. Household VMT is constrained such that annual [<span style="color:green">vehicle operating costs</span>][lexicon] must stay below a maximum share of annual household income, or budget limit. A household-specific average annual vehicle operating costs is first calculated, including out-of-pocket per mile costs for each household owned and Car Service vehicles used by the household, as well as time-equivalent cost (input [<span style="color:green">access times</span>][lexicon], estimates of VMT at congested speeds, and [<span style="color:green">value of time</span>][lexicon] input). Vehicle operating costs determine the proportional split of VMT across household vehicles. Out-of-pocket costs include the energy, maintenance, repair, & tires, [<span style="color:green">road use taxes</span>][lexicon] (including [<span style="color:green">EV surcharge</span>][lexicon] and optional calculation of fee to fully recover road costs), work/non-work parking, [<span style="color:green">PAYD insurance</span>][lexicon], input share of carbon and other [<span style="color:green">social costs</span>][lexicon], as well as [<span style="color:green">CarService</span>][lexicon] fees by the household. 

The following sections describe each module that contributes to this concept.

> Watch a [video overview](https://youtu.be/-ylFbyLfhbw?t=8739) of costs and budgets

### 4.2.1 Auto Ownership Cost & Adjustment

Two steps are required to calculate and adjust auto ownership costs:

1. [_Calculate Vehicle Own Cost:_](https://github.com/gregorbj/Archive-VisionEval/blob/develop/api/VE_Training_March_13-14_2019/VE_Training.md#66-calculatevehicleowncost)  Average [<span style="color:green">vehicle ownership costs</span>][lexicon] are calculated for each vehicle based on the vehicle type, age, and annual VMT (financing, depreciation, and insurance), annual registration fees (flat and ad valorum), combined with any residential [<span style="color:green">parking fees</span>][lexicon] (if household exceeds free parking limits). To do so, [<span style="color:green">PAYD insurance</span>][lexicon] participation is assigned based on household characteristics (drivers by age, annual mileage, income, location type, vehicle type and age) and input PAYD insurance program participation. The ownership cost is converted into an average vehicle-specific ownership cost per mile by dividing by estimated household VMT per vehicle.

    Note that PAYD insurance does not affect the cost of vehicle ownership when determining whether a household will substitute car services for one or more of their vehicles. It does affect the out-of-pocket operating cost used in budget limitations on household VMT.
    
    2. [_Adjust Vehicle Ownership:_](https://github.com/gregorbj/Archive-VisionEval/blob/develop/api/VE_Training_March_13-14_2019/VE_Training.md#67-adjustvehicleownership)  Household vehicle ownership is adjusted based on a comparison of the cost of owning versus 'high' [<span style="color:green">car service</span>][lexicon] per mile rates (from the Household Multimodal Travel module), where available. The module identifies all household vehicles in a 'High' car service area, where the car service mileage rate exceeds the household's estimated [<span style="color:green">vehicle ownership cost</span>][lexicon] per annual household VMT. The household's [<span style="color:green">vehicle table</span>][lexicon] entry changes from 'Own' to 'HighCarSvc' for these vehicles, limited by input assumptions regarding the average likelihood that an owner would substitute [<span style="color:green">car services</span>][lexicon] for a household vehicle (separate values are specified by [<span style="color:green">vehicle type</span>][lexicon]). Other auto ownership values are also updated (e.g., insurance, total vehicles).

### 4.2.2 Auto Operating Cost & Adjustment

Three primary adjustments adjustments to auto operating cost are carried out in VisionEval:

1. [_Calculate Vehicle Operating Cost:_](https://github.com/gregorbj/Archive-VisionEval/blob/develop/api/VE_Training_March_13-14_2019/VE_Training.md#97-calculatevehicleoperatingcost-module)  A composite per mile cost is calculated as an [<span style="color:green">out-of-pocket cost</span>][lexicon] for various household and Car Service vehicle VMT (see below), combined with cost equivalent of travel time (access time and travel time at congested speeds times [<span style="color:green">value of time</span>][lexicon] (VOT)). Total costs result from applying this vehicle-specific cost rate to each vehicle's VMT, where VMT is split among household vehicles (including car services used by household members) as a (reciprocal) function of this vehicle-specific composite cost rate:

    + **Vehicle maintenance, repair, and tire cost (MRT)** costs are calculated as a function of the [<span style="color:green">vehicle type</span>][lexicon], [<span style="color:green">powertrain</span>][lexicon] and [<span style="color:green">vehicle age</span>][lexicon] based on data from the American Automobile Association (AAA) and the Bureau of Labor Statistics (BLS).
    + **Fuel and energy costs** are calculated as energy rates time average fuel efficiency (miles per gallon or Kwhr electricity).
    + **Gas taxes** are federal, state and local per gallon taxes to cover road costs. For Electric vehicles, an equivalent per mile cost is calculated and can be applied to some or all electric vehicles ($/gallon or EV vehicle surcharge tax).
    + **Other Road Cost Recovery taxes** (i.e. VMT tax) is a user input. If the (optional) `BalanceRoadCostsAndRevenues` module is run, an extra VMT tax is calculated that recovers household share of road costs, consistent across all model households.
    + **Congestion fees** are calculated average congestion price ($/mile) for travel on urbanized roads in the Marea multiplied by the proportion of household travel occurring on those roads.
    + **Carbon fee** and **other social cost fees** are carbon cost per mile is calculated as the input [<span style="color:green">carbon price</span>][lexicon] times the average household emissions rate (grams/mile), a VMT-weighting of all vehicles in the household.  Of the other [<span style="color:green">social costs</span>][lexicon], some are per gallon (non-EV vehicle miles) others per mile (regardless of [<span style="color:green">powertrain</span>][lexicon]). The full per mile costs are discounted to only reflect the input proportion of [<span style="color:green">social cost</span>][lexicon] paid by user.
    + Daily **parking costs** from work parking costs (workers who pay for parking) and other parking cost (cost of parking for shopping, etc.) are summed and divided by the household DMVT. Note that residential parking costs are included in the vehicle ownership not per mile cost calculations.
    + **Pay-as-you-drive (PAYD) insurance** is defined for participating households as the sum of the annual insurance cost for all the household vehicles is divided by the annual household VMT.
    + **Car-service costs** are the cost of using a [<span style="color:green">car service</span>][lexicon] (dollars/mile) is a user input by car service level (Low, High).

2. [_Balance Road Costs And Revenues:_](https://github.com/gregorbj/Archive-VisionEval/blob/develop/api/VE_Training_March_13-14_2019/VE_Training.md#99-balanceroadcostsandrevenues-module)  Optionally, an extra mileage tax (\$/mile) for household vehicles needed to make up any difference in the cost of constructing, maintaining, and operating roadways and the revenues from total road cost fees including fuel, VMT, and congestion charges. Optionally, an additional mileage fee ($/mile) on household travel is calculated that would fully pay for roadway costs attributable to household vehicle travel. The cost of existing and new freeway and arterial lane-miles by Marea is calculated from the difference in input lane-miles relative to the base year and input unit [<span style="color:green">road costs</span>][lexicon] (constructing, maintaining, and operating). Reductions in lane-miles are ignored. The proportion of road costs attributable to households is set as the ratio of household VMT divided by the sum of household (including CarService), commercial service, and car-equivalent heavy truck VMT (multiply by [<span style="color:green">PCE</span>][lexicon]). Average road taxes collected per household vehicle mile are calculated as a weighted average of the average road tax per mile of each household (calculated by the `CalculateVehicleOperatingCost` module) using the household VMT (calculated by the `BudgetHouseholdDvmt` module) as the weight. Currently no annual fees contribute to road cost recovery.
3. [_Budget Household Dvmt:_](https://github.com/gregorbj/Archive-VisionEval/blob/develop/api/VE_Training_March_13-14_2019/VE_Training.md#98-budgethouseholddvmt-module)  Household VMT is adjusted to keep within the household's [<span style="color:green">vehicle operating cost</span>][lexicon] budget, based on the historic maximum proportion of income the household is willing to pay for vehicle operations. This proportions varies with income. The household's DMVT is then reduced as needed to keep annual [<span style="color:green">vehicle operating cost</span>][lexicon] within that share of the household's annual income. Annual vehicle operating costs include the household's VMT times their own per mile vehicle costs, adding credits for selected annual payments (annual work parking fee if in a work parking [<span style="color:green">cash-out-buy-back program</span>][lexicon], annual vehicle insurance if in a [<span style="color:green">PAYD insurance program</span>][lexicon], and annual auto ownership costs if [<span style="color:green">car service</span>][lexicon] program reduced auto ownership). The module relies on aggregate survey data from the U.S. Bureau of Labor Statistics (BLS) Consumer Expenditure Survey (CES) for years 2003-2015.
