--- 
title: "VisionEval Concepts Primer"
author: "Tara Weidner, Rick Donnelly, et al."
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [primer.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This is the updated VisionEval Concepts Primer."
---

# Preface {-}

This is the updated VisionEval **Concepts Primer** for beginning users of the system and those wanting a high-level overview of the structure of the system. It includes a brief introduction to the package, describes some typical applications, and describes many of the building blocks of the system. Some of the adjustments made to travel patterns generated in the model are described, followed by a short chapter describing some elements of its implementation. A lexicon collects the definition of keywords or terms that have special meaning in VisionEval in a single place for easy reference. The reader will find a number of special references in the text:

+ Certain keywords have specific meaning when describing constructs in VisionEval, and are colored green in the text. For example, you will see [<span style="color:green">age groups</span>][lexicon] often in the text. These terms are defined in the chapter of this document. The link will take you to the lexicon, where you can scroll to the specific term(s) you are interested in.
+ Links to other documents and websites appear as clickable blue text, like [this link](https://visioneval.org) that will take you to the VisionEval front page.
+ Specific variable or filenames are shown in `offset text`. For example, you might see a reference to the `FudgeFactor` in the `ModuleName` module. These keywords are generally *not* clickable for variable names, but often are for module names.

The Concepts Primer has been generated using [Bookdown](https://bookdown.org/), enabling it to be compiled into both web page and standalone printed document formats.

Please improve the document by updating those parts that seem incomplete or incorrect. You can pose questions or comments to the maintainers through the [issue tracker](https://github.com/VisionEval/VisionEval-Docs/issues) in the VisionEval-Docs repository.
